### ISSUE TITLE
Error while loading single-spa-vue app from portal

### ISSUE THREAD

**Issue by markuman** [me-12/single-spa-portal-example#10]
This is my fork https://github.com/markuman/single-spa-portal-example/

I simply did

* `npx vue create app4vue`

and attache `single-spa-vue`, but when I try to load the portal and click `app4`, I got the following error.
I've absolutly no idea what's wrong with that.

```
Error: 'app4' died in status LOADING_SOURCE_CODE: Module http://localhost:9000/app4/app.js detected as amd but didn't execute correctly.
  Instantiating http://localhost:9000/app4/app.js
  Loading /app4/app.js
```

As far as I understand, the idea is to have multiple teams that work independent on single app. Later they are merged by the portal. But none of the single apps is usable standalone. E.g. wenn doing `npm run watch` in the reactapp, I just receive  `Cannot GET /`.  So the teams can only their result when deploying it over the portal?

**Comment by abelkbil** [comment]
single spa work on builds, npm run watch has to run on dev mode of independent application

**Comment by markuman** [comment]
How should this be helpful?  
Yes, I'm using it with `npm run watch` as mentioned in the `README.md`

**Comment by me-12** [comment]
@markuman 
The vue CLI does provide its own serve task inclusive webpack config and everything that is needed to get your project running when developing the app as standalone. All of that happens in the background. You don't need to take care about that.

What you need to do, is create your own webpack.conf.js just for the portal integration. With this config you will be able to build your app exclusively for the portal (i.e. the portal need a bundled AMD or UMD module and no index.html). 

You can take a look at all those sample apps in this repo. Each app has its own webpack.conf.js which bundles the individual apps so that the portal can load them.

What you end with are separate tasks that build and watch your app EITHER as standalone OR for the portal integration. This way you can develop your app locally without the portal.

I have hacked together a fast example on how this can be achieved. I will upload it tomorrow.

**Comment by me-12** [comment]
@markuman I have updated this repo to include an Vue example app. You can use `npm run watch:portal` to serve your project for the portal. If you just want to use the standalone version use: `npm run watch:standalone`.

I hope this helps.

**Comment by me-12** [comment]
Closing since I assume this issue is fixed. Reopen if you have any further questions.
