### ISSUE TITLE
README - How to run this project - does not start portal

### ISSUE THREAD

**Issue by kbrown** [me-12/single-spa-portal-example#26]
How to run this project
Clone this project
Jump into each folder and do:
npm install
npm run watch:portal
Open up http://localhost:9000 in a web browser.

There is no "npm run watch:portal" script in portal.   It is "npm run watch"

**Comment by me-12** [comment]
Hello @kbrown . Thank you for the hint. Since each app may have a standalone version (which runs without the portal environment) I needed to distinct between those two builds. That's why I introduced two scripts, namely "watch:portal" and "watch.standalone". 

The portal itself has no standalone version obviously, since it is the portal environment itself.

I have updated the documentation to describe the installation process better.
