### ISSUE TITLE
webpack is building the child applications as single main.js file

### ISSUE THREAD

**Issue by abelkbil** [me-12/single-spa-portal-example#4]
Hi,
Thanks for this repo. I was straggling to configure webpack. You saved me. Your sample project's webpack is building the child applications as single main.js file. Is this is the correct way .

If I want to create it as a single application, I need to load it to other single-spa root application

**Comment by me-12** [comment]
The point of this repo is to have separate build processes so that each team can deploy their application individually. 

If you just want to have a single build process to build all your child apps into one big single SPA, you can use the simple webpack example here: https://github.com/joeldenning/simple-single-spa-webpack-example

**Comment by me-12** [comment]
I hope this issue is clarified. Closing for now. If you have any further questions, you can open this issue again.

**Comment by abelkbil** [comment]
Thanks @me-12
