### ISSUE TITLE
Mono Repo version created (need some help for react) FIXED

### ISSUE THREAD

**Issue by tsukhu** [me-12/single-spa-portal-example#45]
@me-12 Thanks for creating this example. It was exactly what I was looking for.
One issue with running this sample is the process of going into each app and building / running it separately. To improve on that I have created a monorepo version of the same using lerna + yarn workspaces. The process of running it is just a two step process a defined in the README. I was planning to submit this as a PR but have run into one issue with the react app. I think I am missing something very basic here , but not able to figure it out. It would be great if you can provide me some incites. 
Here is the project
https://github.com/tsukhu/single-spa-portal-example 

Also once fixed , if you think it is ok , then I will submit this as a PR (after some fine tuning and getting the React app working)

**Comment by tsukhu** [comment]
I was able to fix the mono repo version and make it working for React as well.
Here are the new changes done to make it work https://github.com/tsukhu/single-spa-portal-example/commit/a096a05768be02dd706185bf544d3dd0202c9cc8 

The main being using @babel/plugin-transform-runtime to isolate the react app

**Comment by me-12** [comment]
Hello tsukhu, 

thank you for your work!

I created this repo to give an example on how to run different apps maintained by different teams with different technologies and still create a single website consisting of all those apps. 

So basically, I expect that no one will use my repo exactly like it is. I think it is much more likely, that one team will work on only one app which has its own repo. In this scenario it wouldn't be necessary to use lerna. 

I would also like to not add any more complexity to this repo since I think its already pretty complicated for new people.

Considering those points, I would rather not merge your Fork. But I still like your solution and if you want, I can add a link to your repo in the readme file.

What do you think?

**Comment by tsukhu** [comment]
@me-12 Thank you for your detailed response. It would be great if you could add a link in the Readme.

**Comment by me-12** [comment]
I have added a Link to your fork to the readme.md
https://github.com/me-12/single-spa-portal-example#forks
